import { getDb, schema } from "@/lib/db/client";
import { desc } from "drizzle-orm";
import StatusBadge from "@/components/StatusBadge";
import { SendApplicationButton } from "@/components/ActionButtons";

export const dynamic = "force-dynamic";

export default async function ApplicationsPage() {
  const db = getDb();
  const apps = await db
    .select()
    .from(schema.applications)
    .orderBy(desc(schema.applications.createdAt))
    .limit(200);

  const jobIds = apps.map((a) => a.jobId);
  const jobs = jobIds.length
    ? await db.select().from(schema.jobs)
    : [];
  const jobById = new Map(jobs.map((j) => [j.id, j]));

  return (
    <div className="space-y-3">
      <h2 className="text-sm font-semibold text-neutral-300">{apps.length} applications</h2>
      <div className="space-y-3">
        {apps.map((app) => {
          const job = jobById.get(app.jobId);
          return (
            <div key={app.id} className="rounded border border-neutral-800 p-3">
              <div className="flex flex-wrap items-start justify-between gap-2">
                <div>
                  <div className="font-medium text-white">
                    {job?.title || `Job #${app.jobId}`}
                    {job ? ` @ ${job.company}` : ""}
                  </div>
                  <div className="text-xs text-neutral-400">
                    {app.sendMode === "auto_email" ? "auto-email eligible" : "manual portal apply"} ·
                    generated by {app.generatedBy}
                    {app.sentTo ? ` · sent to ${app.sentTo}` : ""}
                  </div>
                  {job && (
                    <a href={job.url} target="_blank" rel="noreferrer" className="text-xs text-blue-400 hover:underline">
                      open listing →
                    </a>
                  )}
                </div>
                <div className="flex items-center gap-2">
                  <StatusBadge status={app.status} />
                  {app.status === "ready_for_review" && (
                    <SendApplicationButton applicationId={app.id} />
                  )}
                </div>
              </div>
              <details className="mt-2">
                <summary className="cursor-pointer text-xs text-neutral-400">view cover letter</summary>
                <pre className="mt-2 whitespace-pre-wrap rounded bg-neutral-900 p-3 text-xs text-neutral-200">
                  {app.coverLetter}
                </pre>
              </details>
              {app.error && <p className="mt-1 text-xs text-red-400">error: {app.error}</p>}
            </div>
          );
        })}
        {apps.length === 0 && (
          <p className="text-sm text-neutral-500">No applications drafted yet.</p>
        )}
      </div>
    </div>
  );
}
