import { getDb, schema } from "@/lib/infra/db/client";
import { desc, inArray } from "drizzle-orm";
import StatusBadge from "@/components/StatusBadge";
import { SendApplicationButton } from "@/components/ActionButtons";
import DbErrorNotice from "@/components/DbErrorNotice";

export const dynamic = "force-dynamic";

export default async function ApplicationsPage() {
  let apps;
  let jobById;
  try {
    const db = getDb();
    apps = await db
      .select()
      .from(schema.applications)
      .orderBy(desc(schema.applications.createdAt))
      .limit(200);

    // Fetch only the jobs these applications reference. This previously
    // selected the ENTIRE jobs table and then indexed it in memory, so the page
    // got slower with every job ever seen rather than with what it displays.
    const jobIds = [...new Set(apps.map((a) => a.jobId))];
    const jobs = jobIds.length
      ? await db.select().from(schema.jobs).where(inArray(schema.jobs.id, jobIds))
      : [];
    jobById = new Map(jobs.map((j) => [j.id, j]));
  } catch (err) {
    return <DbErrorNotice error={err} />;
  }

  return (
    <div className="space-y-3">
      <h2 className="text-sm font-semibold text-(--text-muted)">{apps.length} applications</h2>
      <div className="space-y-3">
        {apps.map((app) => {
          const job = jobById.get(app.jobId);
          return (
            <div key={app.id} className="rounded border border-(--border) p-3">
              <div className="flex flex-wrap items-start justify-between gap-2">
                <div>
                  <div className="font-medium text-(--text)">
                    {job?.title || `Job #${app.jobId}`}
                    {job ? ` @ ${job.company}` : ""}
                  </div>
                  <div className="text-xs text-(--text-dim)">
                    {app.sendMode === "auto_email" ? "auto-email eligible" : "manual portal apply"} ·
                    generated by {app.generatedBy}
                    {app.sentTo ? ` · sent to ${app.sentTo}` : ""}
                  </div>
                  {job && (
                    <a
                      href={job.url}
                      target="_blank"
                      rel="noreferrer"
                      className="text-xs text-(--text-muted) hover:text-(--text) hover:underline"
                    >
                      open listing →
                    </a>
                  )}
                </div>
                <div className="flex items-center gap-2">
                  <StatusBadge status={app.status} />
                  {app.status === "ready_for_review" && (
                    <SendApplicationButton applicationId={app.id} />
                  )}
                </div>
              </div>
              <details className="mt-2">
                <summary className="cursor-pointer text-xs text-(--text-dim)">view cover letter</summary>
                <pre className="mt-2 whitespace-pre-wrap rounded bg-(--surface) p-3 text-xs text-(--text-muted)">
                  {app.coverLetter}
                </pre>
              </details>
              {app.error && <p className="mt-1 text-xs text-(--danger-fg)">error: {app.error}</p>}
            </div>
          );
        })}
        {apps.length === 0 && (
          <p className="text-sm text-(--text-dim)">No applications drafted yet.</p>
        )}
      </div>
    </div>
  );
}
