import { getDb, schema } from "@/lib/infra/db/client";
import { desc, inArray } from "drizzle-orm";
import StatusBadge from "@/components/StatusBadge";
import { SendOutreachButton } from "@/components/ActionButtons";
import DbErrorNotice from "@/components/DbErrorNotice";

export const dynamic = "force-dynamic";

export default async function OutreachPage() {
  let pitches;
  let leadById;
  try {
    const db = getDb();
    pitches = await db
      .select()
      .from(schema.outreach)
      .orderBy(desc(schema.outreach.createdAt))
      .limit(200);

    // Only the referenced leads — this used to select the whole leads table.
    const leadIds = [...new Set(pitches.map((p) => p.leadId))];
    const leads = leadIds.length
      ? await db.select().from(schema.leads).where(inArray(schema.leads.id, leadIds))
      : [];
    leadById = new Map(leads.map((l) => [l.id, l]));
  } catch (err) {
    return <DbErrorNotice error={err} />;
  }

  return (
    <div className="space-y-3">
      <h2 className="text-sm font-semibold text-neutral-300">{pitches.length} outreach pitches</h2>
      <div className="space-y-3">
        {pitches.map((pitch) => {
          const lead = leadById.get(pitch.leadId);
          return (
            <div key={pitch.id} className="rounded border border-neutral-800 p-3">
              <div className="flex flex-wrap items-start justify-between gap-2">
                <div>
                  <div className="font-medium text-white">
                    {lead?.title || `Lead #${pitch.leadId}`}
                    {lead?.clientOrCompany ? ` — ${lead.clientOrCompany}` : ""}
                  </div>
                  <div className="text-xs text-neutral-400">
                    {pitch.sendMode === "auto_email" ? "auto-email eligible" : "manual - reply via platform"} ·
                    generated by {pitch.generatedBy}
                    {pitch.sentTo ? ` · sent to ${pitch.sentTo}` : ""}
                  </div>
                  {lead && (
                    <a href={lead.url} target="_blank" rel="noreferrer" className="text-xs text-blue-400 hover:underline">
                      open listing →
                    </a>
                  )}
                </div>
                <div className="flex items-center gap-2">
                  <StatusBadge status={pitch.status} />
                  {pitch.status === "ready_for_review" && (
                    <SendOutreachButton outreachId={pitch.id} />
                  )}
                </div>
              </div>
              <details className="mt-2">
                <summary className="cursor-pointer text-xs text-neutral-400">view pitch</summary>
                <pre className="mt-2 whitespace-pre-wrap rounded bg-neutral-900 p-3 text-xs text-neutral-200">
                  {pitch.pitch}
                </pre>
              </details>
              {pitch.error && <p className="mt-1 text-xs text-red-400">error: {pitch.error}</p>}
            </div>
          );
        })}
        {pitches.length === 0 && (
          <p className="text-sm text-neutral-500">No outreach pitches drafted yet.</p>
        )}
      </div>
    </div>
  );
}
