// ---------------------------------------------------------------------------
// Encrypting stored credentials at rest.
//
// Colleagues' SMTP app passwords are the first genuinely sensitive value this
// system stores that it must be able to READ BACK — unlike a login password,
// which only ever needs comparing and is therefore hashed. That difference is
// why this exists alongside password.ts and is not a substitute for it.
//
// AES-256-GCM via Web Crypto: authenticated, so a tampered ciphertext fails to
// decrypt rather than silently yielding garbage that would be handed to an SMTP
// server as a password.
//
// THE KEY IS ITS OWN ENV VAR, deliberately not AUTH_SECRET. AUTH_SECRET signs
// session cookies and is expected to be rotated — the README already says
// changing it signs everyone out, which is a cheap, recoverable consequence.
// If it also encrypted credentials, that same rotation would silently destroy
// every stored mailbox password, and the failure would surface days later as
// applications quietly failing to send.
// ---------------------------------------------------------------------------

const encoder = new TextEncoder();
const decoder = new TextDecoder();

/** Version tag, so the format can change later without ambiguity. */
const VERSION = "v1";
const IV_BYTES = 12; // GCM standard

function toHex(bytes: Uint8Array): string {
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

function fromHex(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

export class EncryptionUnavailableError extends Error {
  constructor() {
    super(
      "ENCRYPTION_KEY is not set, so stored mailbox credentials cannot be read " +
        "or written. Generate one with: openssl rand -hex 32"
    );
    this.name = "EncryptionUnavailableError";
  }
}

/**
 * Derives the AES key from ENCRYPTION_KEY.
 *
 * SHA-256 of the raw value rather than PBKDF2: unlike a user password this is a
 * high-entropy value generated by `openssl rand -hex 32`, so there is nothing
 * for key stretching to defend against, and paying 600k iterations on every
 * send would be cost with no benefit.
 */
async function getKey(): Promise<CryptoKey> {
  const secret = process.env.ENCRYPTION_KEY;
  if (!secret || secret.length < 32) throw new EncryptionUnavailableError();

  const digest = await crypto.subtle.digest("SHA-256", encoder.encode(secret));
  return crypto.subtle.importKey("raw", digest, { name: "AES-GCM" }, false, [
    "encrypt",
    "decrypt",
  ]);
}

/** True when credentials can be stored at all, for the settings UI to check. */
export function encryptionConfigured(): boolean {
  const secret = process.env.ENCRYPTION_KEY;
  return Boolean(secret && secret.length >= 32);
}

/** Returns `v1.<ivHex>.<ciphertextHex>`. A fresh IV per call — never reused. */
export async function encryptSecret(plaintext: string): Promise<string> {
  const key = await getKey();
  const iv = new Uint8Array(IV_BYTES);
  crypto.getRandomValues(iv);

  const ciphertext = await crypto.subtle.encrypt(
    { name: "AES-GCM", iv: iv as BufferSource },
    key,
    encoder.encode(plaintext)
  );

  return `${VERSION}.${toHex(iv)}.${toHex(new Uint8Array(ciphertext))}`;
}

/**
 * Returns null — never throws — for anything that will not decrypt: a rotated
 * key, a truncated column, a tampered value.
 *
 * Null is the right answer because the caller's response is the same in every
 * case: treat the mailbox as unconfigured and queue the draft instead of
 * sending it. Throwing would turn one bad row into a failed pipeline run for
 * everybody.
 */
export async function decryptSecret(stored: string): Promise<string | null> {
  const parts = stored.split(".");
  if (parts.length !== 3 || parts[0] !== VERSION) return null;

  const [, ivHex, dataHex] = parts;
  if (!/^[0-9a-f]+$/.test(ivHex) || !/^[0-9a-f]+$/.test(dataHex)) return null;
  if (ivHex.length !== IV_BYTES * 2) return null;

  try {
    const key = await getKey();
    const plaintext = await crypto.subtle.decrypt(
      { name: "AES-GCM", iv: fromHex(ivHex) as BufferSource },
      key,
      fromHex(dataHex) as BufferSource
    );
    return decoder.decode(plaintext);
  } catch {
    // Wrong key, or GCM's authentication tag rejected the data. Either way
    // this value is unusable.
    return null;
  }
}
